parsing/accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^new_acc/$', views.signup, name='new_acc'),
    url(r'^signin/$', views.signin, name='signin'),
    url(r'^signout/$', views.signout, name='signout'),
]

parsing/cart/urls.py
from django.conf.urls import url
from cart import views


urlpatterns = [
    url(r'^add_product_to_cart/(?P<product_id>[0-9]+)$', views.add_product_to_cart, name='add_product'),
    url(r'^cart_list/$', views.cart_list, name='cart_list'),
]

parsing/linkparser/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
]

parsing/parsing/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from . import settings
from linkparser import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home, name='home'),
    url(r'^parser/', include('linkparser.urls', namespace='parser')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^profiles/', include('profiles.urls', namespace='profiles')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^django-rq/', include('django_rq.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +\
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

parsing/profiles/urls.py
from django.conf.urls import url
from profiles import views

urlpatterns = [
    url(r'^profile/$', views.profile_detail_private, name='profile_detail_private'),
]

parsing/accounts/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

parsing/cart/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
from django.utils import timezone

from linkparser.models import Goods


class CartItem(models.Model):
    product = models.ForeignKey(Goods)
    quantity = models.IntegerField(default=1)
    timestamp = models.DateTimeField(default=timezone.now)

    def __unicode__(self):
        try:
            return str(self.cart.id)
        except:
            return self.product.title


class Cart(models.Model):
    user = models.OneToOneField(User)
    cart = models.ManyToManyField(CartItem, related_name='cart')

parsing/linkparser/models.py
# coding:utf-8
from __future__ import unicode_literals

from django.db import models


class Goods(models.Model):
    title = models.CharField(max_length=255, null=True, blank=True)
    price = models.DecimalField(max_digits=20, decimal_places=2, null=True, blank=True)
    slug = models.SlugField(blank=True)

    class Meta:
        verbose_name = u'Товар'
        verbose_name_plural = u'Товары'

    def __unicode__(self):
        return self.title or u''

parsing/profiles/models.py
# coding: utf-8
from __future__ import unicode_literals
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from django.dispatch import receiver



class Profile(models.Model):
    user = models.OneToOneField(User, verbose_name=u'Пользователь')
    first_name = models.CharField(u'Имя', max_length=255)
    last_name = models.CharField(u'Фамилия', max_length=255)
    create_add = models.DateTimeField(u'Профиль был создан: ', auto_now_add=True)

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def __unicode__(self):
        return self.user.username


@receiver(post_save, sender=User, dispatch_uid="create_profile")
def create_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.get_or_create(user=instance)

parsing/linkparser/forms.py
from django import forms
from models import Goods

class UploadFileForm(forms.Form):
    file = forms.FileField()

parsing/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login as django_login
from django.contrib.auth.models import User
from django.contrib.auth import logout
from django import forms


class SignupForm(forms.ModelForm):

    class Meta:
        model = User
        fields = (
            'first_name', 'last_name', 'username', 'email', 'password'
            )


def signin(request):
    username = request.POST.get('username')
    password = request.POST.get('password')

    user = authenticate(username=username, password=password)
    if user is not None:
        if user.is_active:
            django_login(request, user)
            message = "User is valid, active and authenticated"
            return redirect('/profiles/profile_detail_private/')
        else:
            message = "The password is valid< but the account has bees disabled"
    else:
        message = "The username and password were incorrect"
    return render(request, 'accounts/signin.html', {'error_message': message})


def signup(request):
    form = SignupForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        user.is_active = True
        user.set_password(form.cleaned_data['password'])
        user.save()
        return redirect('/accounts/signin/')
    return render(request, "accounts/signup.html", {'form': form})


def signout(request):
    logout(request)
    return redirect('/')

parsing/cart/views.py
#coding: utf8
from django.db.utils import IntegrityError
from django.shortcuts import render, HttpResponseRedirect, redirect
from django.core.urlresolvers import reverse
from django.contrib import messages
# Create your views here.

from linkparser.models import Goods

from .models import Cart, CartItem


def add_product_to_cart(request, product_id):
    if True:
        product = Goods.objects.get(pk=product_id)
        cart = request.user.cart
        try:
            create = Cart.objects.create(user=request.user)
            create_product = CartItem.objects.create(product=product)
            cart.cart.add(int(create_product.id))
            print create_product
            print cart
        except IntegrityError:
            create_product = CartItem.objects.create(product=product)
            cart.cart.add(int(create_product.id))
            messages.success(request, 'Вы добавили новый товар в корзину')
            return redirect('/')


def cart_list(request):
    user_cart = request.user.cart
    return render(request, 'cart/cart.html', {"cart": user_cart})

parsing/linkparser/views.py
# coding:utf-8
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from models import Goods
from parser_test import excel_reader
from forms import UploadFileForm
from django.contrib import messages
import django_rq


def home(request):
    product = Goods.objects.all().order_by('-id')
    paginator = Paginator(product, 25)
    page = request.GET.get('page')
    try:
        paginator_html = paginator.page(page)
    except PageNotAnInteger:
        paginator_html = paginator.page(1)
    except EmptyPage:
        paginator_html = paginator.page(paginator.num_pages)
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            queue = django_rq.get_queue()
            queue.enqueue(excel_reader, request.FILES['file'])
            messages.success(request, 'Файл был добавлен')
    else:
        form = UploadFileForm()
    return render(request, 'base/base.html', {'form': form, 'paginator_html': paginator_html})

parsing/profiles/views.py
# coding: utf-8
from django.contrib.auth.models import User
from django.shortcuts import render
from .models import Profile


def profile_detail_private(request):
    profile, created = Profile.objects.get_or_create(user=request.user)
    if request.user.is_authenticated:
        return render(request, 'profiles/profile_detail.html', {
            'profile': profile,
        })

parsing/templates/accounts/signin.html
{% extends "base/base.html" %}
{% load static %}
{%  block content %}
<div class="container">
  <div class="row">
        {% if error_message %}
<div class="alert alert-warning" role="alert">
  <a href="#" class="alert-link"></a>
{{ error_message }}
</div>
    {% endif %}
<form class="form-horizontal" method="post"> {% csrf_token %}
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Login</label>
    <div class="col-sm-10">
      <input name="username" class="form-control" id="inputEmail3" placeholder="login">
    </div>
  </div>
  <div class="form-group">
    <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
    <div class="col-sm-10">
      <input name="password" class="form-control" id="inputPassword3" placeholder="Password" type="password">
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <div class="checkbox">
        <label>
          <input type="checkbox"> Remember me
        </label>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Sign in</button>
    </div>
  </div>
</form>


  </div>
</div>

{% endblock %}

parsing/templates/accounts/signup.html
{% extends "base/base.html" %}
{%  block content %}
<div class="container">
    <div class="row">
        <form method="post">{% csrf_token %}
          {{ form.as_p }}
          <input type="submit" value="GO">
        </form>
    </div>
</div>


{% endblock %}

parsing/templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <!-- Standard Meta -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

  <!-- Site Properties -->
  <title>Homepage - Semantic</title>
  <link rel="stylesheet" type="text/css" href="{% static 'Semantic/components/reset.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'Semantic//components/site.css' %}">

  <link rel="stylesheet" type="text/css" href="{% static 'Semantic/components/container.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'Semantic/components/grid.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'Semantic/components/header.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'Semantic/components/image.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'Semantic/components/menu.css' %}">

  <link rel="stylesheet" type="text/css" href="{% static 'Semantic/components/divider.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'Semantic/components/dropdown.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'Semantic/components/segment.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'Semantic/components/button.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'Semantic/components/list.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'Semantic/components/icon.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'Semantic/components/sidebar.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'Semantic/components/transition.css' %}">

  <style type="text/css">

    .hidden.menu {
      display: none;
    }

    .masthead.segment {
      min-height: 700px;
      padding: 1em 0em;
    }
    .masthead .logo.item img {
      margin-right: 1em;
    }
    .masthead .ui.menu .ui.button {
      margin-left: 0.5em;
    }
    .masthead h1.ui.header {
      margin-top: 3em;
      margin-bottom: 0em;
      font-size: 4em;
      font-weight: normal;
    }
    .masthead h2 {
      font-size: 1.7em;
      font-weight: normal;
    }

    .ui.vertical.stripe {
      padding: 8em 0em;
    }
    .ui.vertical.stripe h3 {
      font-size: 2em;
    }
    .ui.vertical.stripe .button + h3,
    .ui.vertical.stripe p + h3 {
      margin-top: 3em;
    }
    .ui.vertical.stripe .floated.image {
      clear: both;
    }
    .ui.vertical.stripe p {
      font-size: 1.33em;
    }
    .ui.vertical.stripe .horizontal.divider {
      margin: 3em 0em;
    }

    .quote.stripe.segment {
      padding: 0em;
    }
    .quote.stripe.segment .grid .column {
      padding-top: 5em;
      padding-bottom: 5em;
    }

    .footer.segment {
      padding: 5em 0em;
    }

    .secondary.pointing.menu .toc.item {
      display: none;
    }

    @media only screen and (max-width: 700px) {
      .ui.fixed.menu {
        display: none !important;
      }
      .secondary.pointing.menu .item,
      .secondary.pointing.menu .menu {
        display: none;
      }
      .secondary.pointing.menu .toc.item {
        display: block;
      }
      .masthead.segment {
        min-height: 350px;
      }
      .masthead h1.ui.header {
        font-size: 2em;
        margin-top: 1.5em;
      }
      .masthead h2 {
        margin-top: 0.5em;
        font-size: 1.5em;
      }
    }


  </style>


</head>
<body>

<!-- Following Menu -->
<div class="ui large top fixed hidden menu">
  <div class="ui container">
    <a class="active item">Главная</a>
    <div class="right menu">
        {% if user.is_authenticated %}
        <div class="content">
         <div class="ui sub header">{{ request.user.username }}</div>
            Project Manager
        </div>
        {% else %}
          <div class="item">
            <a class="ui button">Войти</a>
          </div>
          <div class="item">
            <a class="ui primary button">Зарегаться</a>
          </div>
        {% endif %}
    </div>
  </div>
</div>

<!-- Page Contents -->
<div class="pusher">
  <div class="ui inverted vertical masthead center aligned segment">

    <div class="ui container">
      <div class="ui large secondary inverted pointing menu">
        <a class="toc item">
          <i class="sidebar icon"></i>
        </a>
        <a class="active item" href="{% url 'home' %}">Главная</a>
        <div class="right item">
               {% if user.is_authenticated %}
            <div class="content">
             <div class="ui sub header"><a href="{% url 'profiles:profile_detail_private' %}">{{ request.user.username }}</a></div>
                Project Manager
            </div>
            {% else %}
              <div class="item">
                <a class="ui button">Войти</a>
              </div>
              <div class="item">
                <a class="ui primary button">Зарегаться</a>
              </div>
            {% endif %}
        </div>
      </div>
    </div>

    <div class="ui text container">
      <h1 class="ui inverted header">
        Парсинг тест
      </h1>
      <h2>Just do it.</h2>
        <form action="" class="ui form" enctype="multipart/form-data" method="POST">
            {% csrf_token %}
             <div class="field">
               {{ form.as_p }}
             </div>
             <button class="ui button" type="submit">Submit</button>
        </form>
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>

  </div>
    <ul>
        {% for i in paginator_html %}
        <li>{{ i }}</li>
        <li>{{ i.price }}</li>
        <a href="{% url 'cart:add_product' i.id %}"> добавить в корзину</a>
        {% endfor %}
    </ul>
  <div class="ui vertical stripe segment">
    <div class="ui middle aligned stackable grid container">
      <div class="row">
        {% block content %}{% endblock %}
      </div>
      <div class="row">
        <div class="ui list">
           <div class="item">
               <i class="marker icon"></i>
               <div class="content">
                 {% if paginator_html.has_previous %}
                   <a href="?page={{ paginator_html.previous_page_number }}">previous</a>
                 {% endif %}

                   <span class="current">
                       Page {{ paginator_html.number }} of {{ paginator_html.paginator.num_pages }}
                   </span>

                   {% if paginator_html.has_next %}
                   <a href="?page={{ paginator_html.next_page_number }}">next</a>
                   {% endif %}
               </div>
           </div>
        </div>
      </div>
    </div>
  </div>

  <div class="ui inverted vertical footer segment">
    <div class="ui container">
      <div class="ui stackable inverted divided equal height stackable grid">
        <div class="three wide column">
          <h4 class="ui inverted header">About</h4>
          <div class="ui inverted link list">
            <a href="#" class="item">Sitemap</a>
            <a href="#" class="item">Contact Us</a>
            <a href="#" class="item">Religious Ceremonies</a>
            <a href="#" class="item">Gazebo Plans</a>
          </div>
        </div>
        <div class="three wide column">
          <h4 class="ui inverted header">Services</h4>
          <div class="ui inverted link list">
            <a href="#" class="item">Banana Pre-Order</a>
            <a href="#" class="item">DNA FAQ</a>
            <a href="#" class="item">How To Access</a>
            <a href="#" class="item">Favorite X-Men</a>
          </div>
        </div>
        <div class="seven wide column">
          <h4 class="ui inverted header">Footer Header</h4>
          <p>Extra space for a call to action inside the footer that could help re-engage users.</p>
        </div>
      </div>
    </div>
  </div>
</div>

{% block js %}
  <script src="https://code.jquery.com/jquery-2.2.4.min.js"   integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="   crossorigin="anonymous"></script>
  <script src="{% static 'Semantic/components/visibility.js' %}"></script>
  <script src="{% static 'Semantic/components/sidebar.js' %}"></script>
  <script src="{% static 'Semantic/components/transition.js' %}"></script>
  <script>
  $(document)
    .ready(function() {

      // fix menu when passed
      $('.masthead')
        .visibility({
          once: false,
          onBottomPassed: function() {
            $('.fixed.menu').transition('fade in');
          },
          onBottomPassedReverse: function() {
            $('.fixed.menu').transition('fade out');
          }
        })
      ;

      // create sidebar and attach to menu open
      $('.ui.sidebar')
        .sidebar('attach events', '.toc.item')
      ;

    })
  ;
  </script>
{% endblock %}

</body>

</html>

parsing/templates/cart/cart.html
{% extends 'base/base.html' %}


{% block content %}
{% for i in cart.cart.all %}
    <ul>
        <li>{{ i.product }}</li>
        <li>{{ i.product.price }}</li>
    </ul>
{% endfor %}
{% endblock %}

parsing/templates/cart/cart_add.html
{% extends 'base/base.html' %}


{% block content %}

{% for i in cart.cart %}
    <ul>
        <li>{{ i }}</li>
    </ul>
{% endfor %}

{% endblock %}

parsing/templates/parse/pars.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}




<div class="ui list">
{% for list in paginator_html %}
      <a class="item">
        <i class="right triangle icon"></i>
        <div class="content">
          <div class="header">{{ list }}</div>
          <div class="description desc_new_style">{{ list.price }} USD</div>
            {% if request.user.is_authenticated %}
{#            <form action="" class="ui form" method="POST">#}
                <a href="{% url 'cart:cart' %}">добавить в корзину</a>
                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
{#            </form>#}
            {% endif %}
        </div>
      </a>
{% endfor %}
</div>



{% endblock %}

{% block js %}
{% endblock %}

parsing/templates/profiles/profile_detail.html
{% extends "base/base.html" %}
{% load static %}


{% block content %}
<div class="container">
    <div class="col-md-12">
        <div class="header">
            <div class="header_in">
                <div id='user'>
                    <h3>{{ request.user.username }}</h3>
                </div>
            </div>
        </div>
        <!--  -->
        <div class="row wrap">
            <div class="wrap_in">

                <div class="col-md-9">
                    <div class="profile_info">
                        <div class="bio">
                            <div>
                                <p>{{request.user.get_full_name}}</p>
                                <p><a href="">изменить статус</a></p>
                            </div>

                        </div>
                    </div>

                </div>
                <form action="" method="POST">
                    {% csrf_token %}
                    {{ forms.as_p }}
                    <button>save</button>
                </form>

            </div>
        </div>
    </div>
</div>
{% endblock %}